namespace FluentUISourceGenerator.Builder;

using System.Text;

public static partial  class Templates
{
    public const string ClassTemplate =
        """
        // <auto-generated />
        
        namespace {NAMESPACE} {
            internal static class {CLASS_PREFIX}{CLASS_NAME}{CLASS_POSTFIX} {
        {CONTENT}
        {CUSTOM_CONTENT}
            }
        }
        """;

    public const string MethodForMethodTemplate =
        """
        public static {T_NAME} {METHOD_NAME}<{GENERIC_ARGUMENTS}>(this {T_NAME} t{METHOD_PARAMETERS}) {METHOD_CONSTRAINTS} {
            
            t.{CALLED_METHOD_NAME}({CALLED_METHOD_ARGUMENTS});
            
            return t;
        }
        """;

    public const string MethodForPropertyTemplate =
        """
        public static {T_NAME} {METHOD_NAME}<{GENERIC_ARGUMENTS}>(this {T_NAME} t, {PROPERTY_TYPE} {PROPERTY_NAME}) {METHOD_CONSTRAINTS} {
        
            t.{PROPERTY_NAME} = {PROPERTY_NAME};
        
            return t;
        }
        """;

    public const string GenericBindMethodForPropertyTemplate =
        """
        public static {T_NAME} Bind{METHOD_NAME}<{GENERIC_ARGUMENTS}>(this {T_NAME} t, UnityEngine.UIElements.Binding binding) {METHOD_CONSTRAINTS} {
            
            t.SetBinding(Properties.{PROPERTY_NAME}, binding);
            
            return t;
        }
        """;

    public const string BindMethodForPropertyTemplate =
        """
        public static {T_NAME} Bind{METHOD_NAME}<{GENERIC_ARGUMENTS}>(this {T_NAME} t, System.String propertyName, System.Object localDataSource = null, UnityEngine.UIElements.BindingMode bindingMode = UnityEngine.UIElements.BindingMode.ToTarget) {METHOD_CONSTRAINTS}
            => t.Bind{METHOD_NAME}<{GENERIC_ARGUMENTS}>(BindingsRepository.GetCachedOrCreateBinding(propertyName, localDataSource, bindingMode));
        """;

    public const string MethodForEventTemplate =
        """
        public static {T_NAME} {METHOD_NAME}<{GENERIC_ARGUMENTS}>(this {T_NAME} t, {EVENT_TYPE} {EVENT_NAME}) {METHOD_CONSTRAINTS} {
            
            t.{EVENT_NAME} += {EVENT_NAME};
            
            return t;
        }
        """;

    public const string BindingTemplate =
        """
        public static readonly UnityEngine.UIElements.BindingId {FIELD_NAME} = (UnityEngine.UIElements.BindingId) "{BINDING_ID}";
        """;

    public const string MethodForStylePropertyTemplate =
        """
        public static {T_NAME} Style{METHOD_NAME}<{GENERIC_ARGUMENTS}>(this {T_NAME} t, {PROPERTY_TYPE} {PROPERTY_NAME}) {METHOD_CONSTRAINTS} {

            t.style.{PROPERTY_NAME} = {PROPERTY_NAME};

            return t;
        }
        """;

    public static string Render(this string template, ITemplateData data)
    {
        var stringBuilder = new StringBuilder(template);
        foreach (var d in data.ToDictionary())
        {
            stringBuilder.Replace("{" + d.Key + "}", d.Value);
        }
        return stringBuilder.ToString();
    }
}
